services:

    dineromail-api.form.type:
        class: %dineromail-api.form.type.class%
        arguments:
            router: @router
            payment.bridge: @payment.bridge
            dineromail-api.controller.route.name: %dineromail-api.controller.route.name%
        tags:
            - { name: form.type, alias: dineromail-api_view }

    dineromail-api.manager:
            class: %dineromail-api.manager.class%
            arguments:
                payment.event.dispatcher: @payment.event.dispatcher
                payment.bridge: @payment.bridge
                dineromail-api.api_user_name: %dineromail-api.api_user_name%
                dineromail-api.api_password: %dineromail-api.api_password%
                logger: @logger
                ns: %dineromail-api.ns%
                dineromail-api.api_prefix: %dineromail-api.api_prefix%

    dineromail-api.twig.extension:
        class: %dineromail-api.twig.extension.class%
        arguments:
            form.factory: @form.factory
            payment.bridge: @payment.bridge
        tags:
            - { name: twig.extension }

    dineromail-api.routes.loader:
        class: %dineromail-api.routes.loader.class%
        arguments:
          dineromail-api.controller.route.name: %dineromail-api.controller.route.name%
          dineromail-api.controller.route: %dineromail-api.controller.route%
        tags:
            - { name: routing.loader }